//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonDirectory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonConnection
    {
        public int ID { get; set; }
        public int OriginatorID { get; set; }
        public int TargetID { get; set; }
        public int TypeID { get; set; }
    
        public virtual ConnectionType ConnectionType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
